######## COMPONENTS MENU

[[components]]
  name = "Foundation"
  weight = 1
  identifier = "foundation"
  url = "/foundation/"

[[components]]
  name = "Content text"
  weight = 5
  identifier = "getting-started"
  url = "/getting-started/"

[[components]]
  name = "Buttons and links"
  weight = 15
  identifier = "themes"
#  post = "break"
  url = "/themes/"

[[components]]
  name = "Form elements"
  weight = 20
  identifier = "content-management"
  post = "expanded"
  url = "/content-management/"

[[components]]
  name = "Icons"
  weight = 25
  identifier = "templates"

  url = "/templates/"

[[components]]
  name = "Miscellaneous"
  weight = 30
  identifier = "functions"
  url = "/functions/"




######## PRINCIPLES MENU

[[principles]]
  name = "UX principles"
  weight = 5
  identifier = "pipes"
  url = "/hugo-pipes/"

[[principles]]
  name = "UI principles"
  weight = 10
#  post = "break"
  identifier = "commands"
  url = "/commands/"

[[principles]]
  name = "Dev principles"
  weight = 30
  identifier = "troubleshooting"
  url = "/troubleshooting/"


# LOW LEVEL ITEMS

# [[docs]]
#   name = "Troubleshooting"
#   weight = 60
#   identifier = "troubleshooting"
#   url = "/troubleshooting/"

#[[docs]]
#  name = "Tags"
#  weight = 120
#  identifier = "tags"
#  url = "/tags/"


# [[docs]]
#   name = "Categories"
#   weight = 140
#   identifier = "categories"
#   url = "/categories/"

######## QUICKLINKS

#  [[quicklinks]]
#    name = "Fundamentals"
#    weight = 1
#    identifier = "fundamentals"
#    url = "/tags/fundamentals/"




######## PRIMARY NAV

  [[global]]
    name = "Principles"
    weight = 5
    identifier = "principles"
    url = "/principles/"

  [[global]]
    name = "Components"
    weight = 10
    identifier = "components"
    url = "/components/"

  [[global]]
    name = "Documentation"
    weight = 15
    identifier = "documentation"
    url = "/documentation/"

  # Anything with a weight > 100 gets an external icon
  #   [[global]]
  #     name = "Community"
  #     weight = 150
  #     icon = true
  #     identifier = "community"
  #     post = "external"
  #     url = "https://discourse.gohugo.io/"
